# ----------------------- #
#   目录结构配置          #
# ----------------------- #
# 默认（推荐）的目录结构如下
#(.)
# |
# +- site 第一个站点(博客)，默认站点
# |   |
# |   +- config.yml (站点的配置文件)
# |   |
# |   +- source (所有带有 YAML 头的站点有源文件，和静态文件)
# |   |
# |   +- templates (所有 FreeMarker 模板)
# |   |
# |   +- assets (静态资源，也可以直接放在 source 目录中)
# |  
# +- site2 第二个站点，目录结构同第一个
# |
# +- target 目标目录，可安全删除
#     |
#     +- public 静态网站（博客）的输出目录，每个站点一个子目录
#     |    |
#     |    +- site 第一个站点的输出目录
#     |    |
#     |    +- site2 第二个站点的输出目录
#     |
#     +- sass-cache SASS编译时的临时缓存目录
#     |
#     +- work 工作目录
#


# 指定站点目录，默认是当前文件所在的目录。对于站点中的子目录，有以下要求（或规则）
#   source：        必须存在
#   templates：如果该目录不存在，则取目录 ‘source/_templates’。二者之一必须存在。
#   assets:    如果该目录不存在，则表示所有的静态资源都在 ‘source’ 目录中，并没有单独
#                分出来。为了站点生成效率，建议将静态资源分离出来单独放置在该目录中。
# 进行版本管理（备份）时，管理 ‘site’ 目录即可。
# site: site

# 站点生成的目标目录。如果需要在本机发布（调试），该目录可以是 ‘/var/www/html’。
# 如果不指定，默认在 ‘site’ 父级目录中创建 ‘target/public/${site}’ 作为该属性的值(site 变量取自上一项配置)。
# destination: target/public/site

# 工作目录。用于生成站点时的中间过程和模板缓存等。
# 如果不指定，默认在 java 临时文件夹中创建 'opoopresscache/${site} 用作工作目录。
# 参考 java 属性 java.io.tmpdir
# working_dir: target/work/site

# ----------------------- #
#      主要配置           #
# ----------------------- #

locale: zh_CN


url: http://www.opoopress.com
title: OpooPress
subtitle: 基于 Java 的静态博客生成器
author: Alex Lin
simple_search: http://google.com/search
description: "OpooPress 博客系统是一个基于 Java 的静态博客生成器，同时也是一个静态网站生成器。"
keywords: "java, 静态博客生成器, 静态网站生成器, OpooPress, 博客, 静态博客"

# 默认的日期格式是 "ordinal"(相当于 java 日期格式的 "MMM d yyyy"，输出 "四月 15 2013")
# 可以直接指定一个 java 日期格式字符串，例如 "yyyy年MM月dd日"
date_format: "ordinal"

# RSS 订阅使用的 URL
subscribe_rss: http://www.opoopress.com/zh/atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# 如果发布到子目录如 http://site.com/project 则设置 'root: /project'
root: /zh
theme_root: '//static.opoo.org/themes/classic-white-op'
default_theme_root: '//static.opoo.org/themes/default'

# 固定链接支持的变量 ：
# 		post 的 front-matter 头部变量 ，以及 ${year}, ${month}, ${day}, ${hour}, ${minute}, ${second}, ${name}, ${pathToFile}, ${fileName} 
permalink: /article/${name}/
# permalink_label: "&infin;"
# permalink_label_feed: "&#9875; 固定链接"

# 新建文章的文件全路径（相对于 source 目录），支持变量 : {year}, ${month}, ${day}, ${hour}, ${minute}, ${second}, ${name}, ${title}, ${date}
new_post: article/${year}-${month}-${day}-${name}.markdown

# 新建页面的文件全路径（相对于 source 目录），支持变量  : ${year}, ${month}, ${day}, ${hour}, ${minute}, ${second}, ${name}, ${title}, ${date}
new_page: ${name}.markdown

# 分类所在的目录
category_dir: /category

# 分类目录名称与标题对照关系。通常名称用于组成 URL，小写切不含空格，标题则用于显示。
# 未在此处指定的分类 OpooPress 会自行处理。
category_names: {"opoopress": "OpooPress", "blog": "博客"}

# Category title prefix.
category_title_prefix: "分类: "

# 标签所在的目录
tag_dir: /tag

# 标签名称与标题对照关系。通常名称用于组成 URL，小写切不含空格，标题则用于显示。
tag_names: {"opensource":"开源项目"}

# 标签标题前缀
tag_title_prefix: "标签："

# 首页每页显示的文章数
paginate: 10          		

# 要显示的最新文章数
recent_posts: 5

# 相关文章的最大数量
related_posts: 5   	

# 在显示摘要的文章中'继续阅读'的按钮文字
excerpt_link: "继续阅读"

# 摘要在文章中的分隔标识
excerpt_separator: "<!--more-->"

# 文章或者页面的标题是否使用 titlecase
titlecase: true

# 主导航菜单
navs: {"首页": "/zh/", "博客": "/zh/blog/", "下载": "/zh/download/", "文档": "/zh/docs/", "帮助": "/zh/help/", "源码": "https://github.com/opoo/opoopress"}
#, "English": "/en/"

# 侧边栏默认包含的模板数组。
# 被设置的模板片段应该位于  [模板路径]/asides 目录，例如 site/templates/asides 或者 site/source/_templates/asides.
default_asides: [recent_posts.ftl, recent_comments.ftl]

# 首页侧边栏包含的模板，未设置使用 default_asides
# blog_index_asides:
# 文章页面侧边栏包含的模板，未设置使用 default_asides
# post_asides:
# 普通页面侧边栏包含的模板，未设置使用 default_asides
# page_asides: [docs_index.ftl]

source_base_path: https://raw.github.com/opoo/opoopress.com/master/zh/source
source_link: 本页源码


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: 
github_repo_count: 0
github_show_profile_link: false
github_skip_forks: true

# Twitter
twitter_user:
twitter_tweet_button: false

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 
googleplus_hidden: false

# Pinboard
pinboard_user: 
pinboard_count: 3

# Delicious
delicious_user: 
delicious_count: 3

# Disqus Comments
disqus_short_name: opoopress
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-42112065-1
google_analytics_tracking_domain:

# Facebook Like
facebook_like: false


# ----------------------- #
#   Deployment Settings   #
# ----------------------- #
# deploy_server: {id: my_vps_server, url: 'scp://my.vps.ip/var/www/html', user: 'ssh_username'}



###############################################################################
## 以下配置主要给开发人员使用，如果您不做二次开发或者不清楚各个参数的含义，
## 请勿修改以下的各个参数 
###############################################################################

# ----------------------- #
#   PlugIns Settings      #
# ----------------------- #
# plugins: 
#  - org.opoo.press.plugin.SamplePlugin


# ------------------------ #
# Default PlugIn Settings  #
# ------------------------ #
converters:
  - org.opoo.press.converter.TxtmarkMarkdownConverter

generators:
  - org.opoo.press.generator.PaginationGenerator
  - org.opoo.press.generator.CategoryGenerator
  - org.opoo.press.generator.TagGenerator
  - com.opoopress.website.DocsGenerator
  
# siteFilters:
#  - org.opoo.press.filter.SampleSiteFilter
#siteFilters:
# - org.opoo.press.filter.FixUrlSiteFilter

# SlugHelper
slugHelper: org.opoo.press.slug.ChineseToPinyinSlugHelper

# ----------------------- #
#   Code Block Settings   #
# ----------------------- #

# Default use 'SyntaxHighlighter' as the highlighter code block processor
# http://alexgorbatchev.com/SyntaxHighlighter/
highlighter: "org.opoo.press.highlighter.SyntaxHighlighter"


# ----------------------- #
#   FreeMarker config     #
# ----------------------- #

# auto_import_templates:{"ns" : "template_name.ftl", "ns2" : "template2_name.ftl"}
# auto_include_templates: ["global_template1.ftl", "global_template2.ftl"]


